---
#file: roles/common/defaults

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# default variables for the role (see Using Variables for more information).
# These variables have the lowest priority of any variables available,
# and can be easily#overridden by any other variable, including inventory variables.

common_rpms: ['chrony', 'nfs-utils', 'nfs4-acl-tools', 'wget']

