---
# roles/kubernetes-kubeuser/tasks

- name: crear el usuario "{{ kubeuser }}" para gestionar kubernetes
  user:
    name: "{{kubeuser}}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    comment: usuario kubernetes
  become: yes
 
- name: crear directorio /home/{{ kubeuser }}/.kube
  file:
    path: /home/{{ kubeuser }}/.kube
    state: directory
    owner: "{{ kubeuser }}"
    group: "{{ kubeuser }}"
    mode: '770'
  become: yes

#- name: copiar el directorio de configuracion /etc/kubernetes/admin.conf a /home/{{ kubeuser }}/.kube/config 
#  command: cp /etc/kubernetes/admin.conf /home/"{{ kubeuser }}"/.kube/config 
#  args:
#    warn: false
#  become: yes  
  
- name: configuracion de permisos sobre /home/{{ kubeuser }}/.kube/config
  file:
    path: /home/{{ kubeuser }}/.kube/config
    owner: "{{ kubeuser }}"
    group: "{{ kubeuser }}"
    mode: '660'
  become: yes  

- name: fichero sudoer en /etc/sudoers.d/200-{{kubeuser}}
  copy:
    content: '{{kubeuser}} ALL=(ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/{{kubeuser}}
    remote_src: yes
    validate: /usr/sbin/visudo -csf %s
  become: yes  
  