---
# roles/kubernetes-common/tasks

- name: activar transparent masquerading vxlan protocol
  command: modprobe br_netfilter 
  become: yes
  
- name: activar transparent masquerading vxlan protocol
  command: modprobe br_netfilter 
  become: yes
  
- name: activar transparent masquerading en firewall-cmd
  command: firewall-cmd --add-masquerade --permanent 
  become: yes
  ignore_errors: true

- name: reload firewall-cmd
  command: firewall-cmd --reload 
  become: yes
  ignore_errors: true
  
- name: mejoras configuracion - sysctl k8s.conf
  copy:
    src: files/k8s.conf 
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
  become: yes
  
- name: aplicando cambios en el sistema
  command: sysctl --system 
  become: yes

- name: deshabilitar memoria swap
  command: swapoff -a
  become: yes

- name: deshabilitar memoria swap en fstab
  lineinfile: 
    dest: /etc/fstab
    regexp: '^(.*)swap(.*)$'
    state: absent
    backrefs: yes
  become: yes

- name: instalar docker 19.03 y containerd
  dnf:
    name:
      - docker-ce-19.03.14-3.el8
      - containerd.io
    enablerepo: https://download.docker.com/linux/centos/docker-ce.repo
    state: present
  become: yes  

- name: habilitar el servicio de docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: habilitar el repositorio de paquetes de kubernetes
  copy:
    src: files/kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
  become: yes

- name: instalar kubernetes 
  dnf:
    name:
      - kubelet
      - kubeadm
    disable_excludes: kubernetes
    state: present
  become: yes
  #install kubelet kubeadm kubectl --disableexcludes=kubernetes -y

- name: habilitar servicio kubernetes
  systemd:
    name: kubelet
    state: started
    enabled: yes
  become: yes
  