---

#- name: deploy common tasks
#  hosts: all
#  gather_facts: true
#  roles:
#    - common

#- name: deploy nfs server
#  hosts: nfs
#  gather_facts: true
#  roles:
#    - nfs

#- name: deploy common kubernetes config
#  hosts: master,workers
#  gather_facts: true
#  roles:
#    - kubernetes-common

- name: deploy kubernetes master y workers
  hosts: master
  gather_facts: true
  roles:
    - kubernetes-master
    - kubernetes-workers
 